#import "../template.typ": *

= Chapter 2: Orbit Perturbations and Propagations

== Orbit Perturbations

For Keplerian orbits, the planet is assumed to be a point mass with no external forces acting. However for real spacecraft and satellites in orbit there exist disturbances which affect the motion of satellites in orbit. Though the central force from the body often dominates, some other perturbations include:

- Aerodynamic drag
- Solar radiation pressure
- Gravitational perturbations from a non-uniform, non-spherical central body
- Third body perturbations
- Electromagnetic drag
- Relativistic effects
- Yarkovsky-O'Keefe-Radzievskii-Paddack (YORP) effect from thermal radiation emission
- Outgassing, leaking and low thrust

A plot of the relative strength of these various disturbances for a LEO 2U CubeSat are shown in *@3-pertubations-1* and for a larger satellite in *@3-pertubations-2*.

#grid(
  column-gutter: 1cm,
  columns: 2,
  [
    #figure(
      image("images/3-pertubation-effects-1.png", width: 100%),
      caption: [Relative strength of perturbations on a 2U CubeSat in LEO.],
      supplement: [Figure],
      kind: figure,
    )<3-pertubations-1>
  ],
  [
    #figure(
      image("images/3-pertubation-effects-2.png", width: 80%),
      caption: [Relative strength of perturbations on a large satellite in LEO.],
      supplement: [Figure],
      kind: figure,
    )<3-pertubations-2>
  ],
)

=== Aerodynamic Drag

The interaction os a spacecraft with the upper atmosphere can sap away energy from the orbit. Below 500km and even more significantly below 150km, drag acts to decrease the apogee of the orbit. The equation for drag is shown in *@3-drag*.

$
  a_"drag" = 1/2 rho(r) v^2 C_d A/m
$<3-drag>

Typically $C_d approx 2.2$ and the $A"/"m$ is assumed to be an average parameter. The air density $rho$ itself is a parameter based on several variables such as position, altitude, solar activity etc. One simplified model of the air density is shown in *@3-simple-air-density*.

$
  rho = rho_0 exp(-h/H) quad quad H = (k T)/(m g)
$<3-simple-air-density>

Where $H$ is the scale height. Another problem arises as $H(T)$ and $T(r)$. The temperature throughout the atmosphere varies as shown in *@3-temp-plot*.

#grid(
  columns: 2,
  column-gutter: 1cm,
  [#figure(
    image("images/3-temperature-plot.png", width: 110%),
    caption: [Plot of temperature throughout the atmosphere.],
    supplement: [Figure],
    kind: figure,
  )<3-temp-plot>],
  [#figure(
    image("images/3-piecewise-density-model.png", width: 100%),
    caption: [Table of piecewise density model data.],
    supplement: [Figure],
    kind: figure,
  )<3-piecewise-density-table>],
)

A slightly better approach to model the atmosphere is a piecewise model whereby for a given altitude a base height is provided creating a piecewise density model, shown in *@3-piecewise-density-table* and in *@3-piecewise-density-equation*.

$
  rho = rho_0 exp(-(h - h_0)/H)
$<3-piecewise-density-equation>

For high speed reentry of spacecraft the above models are insufficient as the atmosphere is not an ideal gas. For high speed upper atmosphere re-entry (Knudsen number $gt.eq$ 1) a Direct Simulation Monte-Carlo (DSMC) is used to extract temperatures dynamic pressures etc. Below this at lower speeds (Knudsen number $<$ 1) CFD is used. Note the *main parameter to control the atmospheric drag is the $A/m$ ratio*.

=== Solar Radiation Pressure

Photons from the sun impart a small amount of momentum when they collide with a surface. Solar sails make use of this to gain $Delta v$ directly from sunlight instead of a thruster. The momentum change by a photon being absorbed as well as being reflected is shown in *@3-solar-radiation-momentum*.

$
  Delta p_"absorbed" = E/c quad quad quad
  Delta p_"reflected" = (2 cos(alpha) E)/c
$<3-solar-radiation-momentum>

These equations can be written in terms of pressure by using $P=F"/"A$, $F= Delta p "/" Delta t$ and $A_"eff" = A cos (alpha)$ to yield *@3-solar-radiation-pressure*. Note that for absorption the resulting force is in the direction of the light whereas for reflection the resulting force is normal to the reflective surface.

$
  P_"Absorption" = W / (c (r/(1 A U))^2) cos(alpha) quad quad
  P_"Reflection" = 2 W / (c (r/(1 A U))^2) cos(alpha)^2
$<3-solar-radiation-pressure>

=== Gravitational Perturbations

==== Issued with Modelling as a Point Mass

If the planet is a sphere of uniform density, or a sphere with shells of varying density then both of these scenarios allow for modelling of said planet as a point mass. The force generated by this equivalent point mass is the same as the central body. However, there are further perturbations such as equator bulge, moving molten mantel, seas and mountains which all perturb the gravitational field.

==== Mesh Grid Modelling

If there exist high resolution images of the body, then a mesh grid approach can be used where finite elements mesh teh body into small chunks. Equations can be solved over these chunks to generate gravitational fields. Though this is good for irregular bodies and does generate a high fidelity model, the generation of said model is very computationally intensive and also requires understanding of the internal structure of the body.

==== Surrogate Modelling

If instead the exact structure is not known of the body a surrogate model can be used which approximates the body as a collection of shapes with constant density. The gravitational potential field can then be determined easily for the body with a low computational cost at the downside of low fidelity.

==== Spherical Harmonics

A more complex method for modelling spherical bodies is spherical harmonics. Effectively a three dimensional Fourier transform where modes are added to approximate the gravitational behaviour of a spherical body. An example of some of these modes are shown in *@3-spherical-harmonics*.

#figure(
  image("images/3-spherical-harmonics.png", width: 50%),
  caption: [Different spherical harmonic modes, with J2 emphasized],
  supplement: [Figure],
  kind: figure,
)<3-spherical-harmonics>

The most significant of these perturbations is J2 which describes the bulging out of the equator of the planet due to its rotation. Its effect on the orbit is a net precession of teh RAAN (right accension of the ascending node ($Omega$) is the point where the orbit cuts the equator). This allows for sun synchronous orbits where the position of the sun relative to the spacecraft doesn't change.
